#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$script_dir" || exit 1

echo "Cleaning scripts/ directory..."
# Move all projects that are generated by the script to a temp directory
mkdir -p temp

echo "NOTE: Ensure to modify this script to exclude the files that should not be moved to the temp directory."

# Find and move all files except those specified
find . -maxdepth 1 -type f ! -name "build.xml" \
    ! -name "apply-build-patch.sh" \
    ! -name "Makefile" \
    ! -name "mutation.sh" \
    ! -name "program-config-status.csv" \
    ! -name "mutation-prerequisites.md" \
    ! -name "mutation-repro.md" \
    ! -name "mutation-all.sh" \
    ! -name "clean-script-dir.sh" \
    ! -name "get-all-subject-src.sh" \
    ! -name "usejdk.sh" \
    -exec mv {} temp/ \;

echo "All files generated by the script have been moved to temp/ directory."
