#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$script_dir" || exit 1

echo "Cleaning scripts/ directory..."
# Move all projects that are generated by the script to a temp directory
mkdir -p temp

echo "NOTE: Ensure to modify this script to exclude the files that should not be moved to the temp directory."

# Find and move all files except those specified
find . -maxdepth 1 -type f ! -name "build.xml" \
    ! -name "build-evosuite.xml" \
    ! -name "pom.xml" \
    ! -name "generate-mvn-dependencies.sh" \
    ! -name "mutation-evosuite.sh" \
    ! -name "apply-build-patch-evosuite.sh" \
    ! -name "apply-build-patch-randoop.sh" \
    ! -name "get-all-subject-src.sh" \
    ! -name "Makefile" \
    ! -name "mutation.sh" \
    ! -name "program-config-status.csv" \
    ! -name "mutation-repro.md" \
    ! -name "mutation-prerequisites.md" \
    ! -name "mutation-evosuite-repro.md" \
    ! -name "mutation-all.sh" \
    ! -name "run-some.sh" \
    ! -name "clean-script-dir.sh" \
    -exec mv {} temp/ \;

    # NOTE: run-some.sh is not by default in the scripts/ directory, but users may have it in their project
    # to run a subset of the test cases. If you have files that should not be moved to the temp directory,
    # add them to the list above.

echo "All files generated by the script have been moved to temp/ directory."
