#!/bin/bash
echo "Clean scripts/ directory to only contain the necessary files for the project."
# Move all projects that are generated by the script to a temp directory
mkdir -p temp

echo "NOTE: Ensure to modify this script to exclude the files that should not be moved to the temp directory."

# Find and move all files except those specified
find . -maxdepth 1 -type f ! -name "build.xml" \
    ! -name "build-evosuite.xml" \
    ! -name "pom.xml" \
    ! -name "generate-mvn-dependencies.sh" \
    ! -name "mutation-evosuite.sh" \
    ! -name "apply-build-patch.sh" \
    ! -name "Makefile" \
    ! -name "mutation.sh" \
    ! -name "project-config-status.csv" \
    ! -name "mutation-repro.md" \
    ! -name "mutation-prerequisites.md" \
    ! -name "mutation-evosuite-repro.md" \
    ! -name "mutation-all.sh" \
    ! -name "run-some.sh" \
    ! -name "clean-dir.sh" \
    -exec mv {} temp/ \;

    # NOTE: run-some.sh is not by default in the scripts/ directory, but users may have it in their project
    # to run a subset of the test cases. If you have files that should not be moved to the temp directory,
    # add them to the list above.

echo "Non-essential files moved to temp/ directory."
