echo "Reset scripts/ directory to only contain the necessary files for the project."
# Move all projects that are generated by the script to a temp directory
mkdir -p temp

echo "NOTE: Ensure to modify this script to exclude the files that should not be moved to the temp directory."

# Find and move all files except those specified
find . -maxdepth 1 -type f ! -name "build.xml" \
    ! -name "diff-patch.sh" \
    ! -name "Makefile" \
    ! -name "mutation.sh" \
    ! -name "project-config-status.csv" \
    ! -name "reproinstructions.txt" \
    ! -name "run-all.sh" \
    ! -name "clean-dir.sh" \
    -exec mv {} temp/ \;

echo "Non-essential files moved to temp/ directory."