mkdir -p ../subject-programs/src
cd ../subject-programs/src
git clone git@github.com:randoop/grt-a4j-1.0b a4j-1.0b
git clone git@github.com:randoop/grt-asm-5.0.1 asm-5.0.1
git clone git@github.com:randoop/grt-bcel-5.2 bcel-5.2
git clone git@github.com:randoop/grt-ClassViewer-5.0.5b ClassViewer-5.0.5b
git clone git@github.com:randoop/grt-commons-cli-1.2 commons-cli-1.2
git clone git@github.com:randoop/grt-commons-codec-1.9 commons-codec-1.9
git clone git@github.com:randoop/grt-commons-collections4-4.0 commons-collections4-4.0
git clone git@github.com:randoop/grt-commons-compress-1.8 commons-compress-1.8
git clone git@github.com:randoop/grt-commons-lang3-3.0 commons-lang3-3.0
git clone git@github.com:randoop/grt-commons-math3-3.2 commons-math3-3.2
git clone git@github.com:randoop/grt-commons-primitives-1.0 commons-primitives-1.0
git clone git@github.com:randoop/grt-dcParseArgs-10.2008 dcParseArgs-10.2008
git clone git@github.com:randoop/grt-easymock-3.2 easymock-3.2
git clone git@github.com:randoop/grt-fixsuite-r48 fixsuite-r48
git clone git@github.com:randoop/grt-guava-16.0.1 guava-16.0.1
git clone git@github.com:randoop/grt-hamcrest-core-1.3 hamcrest-core-1.3
git clone git@github.com:randoop/grt-javassist-3.19 javassist-3.19
git clone git@github.com:randoop/grt-javax.mail-1.5.1 javax.mail-1.5.1
git clone git@github.com:randoop/grt-jaxen-1.1.6 jaxen-1.1.6
git clone git@github.com:randoop/grt-jcommander-1.35 jcommander-1.35
git clone git@github.com:randoop/grt-jdom-1.0 jdom-1.0
git clone git@github.com:randoop/grt-joda-time-2.3 joda-time-2.3
git clone git@github.com:randoop/grt-JSAP-2.1 JSAP-2.1
git clone git@github.com:randoop/grt-jvc-1.1 jvc-1.1
git clone git@github.com:randoop/grt-nekomud-r16 nekomud-r16
git clone git@github.com:randoop/grt-pmd-core-5.2.2 pmd-core-5.2.2
git clone git@github.com:randoop/grt-sat4j-core-2.3.5 sat4j-core-2.3.5
git clone git@github.com:randoop/grt-shiro-core-1.2.3 shiro-core-1.2.3
git clone git@github.com:randoop/grt-slf4j-api-1.7.12 slf4j-api-1.7.12
git clone git@github.com:randoop/grt-tiny-sql-2.26 tinySQL-2.26
